<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<div class="content-box">
<?php $_orders = $block->getOrders(); ?>
<?= $block->getChildHtml('info') ?>
<?php if ($_orders && count($_orders)): ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= /* @escapeNotVerified */ __('Orders') ?></caption>
            <thead style="display: none;">
                <tr>
                    <th scope="col" class="col id"><?= /* @escapeNotVerified */ __('Order #') ?></th>
                    <th scope="col" class="col date"><?= /* @escapeNotVerified */ __('Date') ?></th>
                    <?= /* @noEscape */ $block->getChildHtml('extra.column.header') ?>
                    <th scope="col" class="col shipping"><?= /* @escapeNotVerified */ __('Ship To') ?></th>
                    <th scope="col" class="col total"><?= /* @escapeNotVerified */ __('Order Total') ?></th>
                    <th scope="col" class="col status"><?= /* @escapeNotVerified */ __('Status') ?></th>
                    <th scope="col" class="col actions"><?= /* @escapeNotVerified */ __('Action') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php
                    foreach ($_orders as $_order):
                        $_items = $_order->getAllVisibleItems();
//                            echo "产品名称：" . $_item->getName();
//                            echo "产品数量：" . intval($_item->getQtyOrdered());
//                            //getImageUrl方法第二个参数可选值为Olight/default/etc/view.xml中image标签id属性值
//                            echo "产品缩略图：" . $block->getImageUrl($_item->getProductId(), 'product_small_image');

                    ?>
                        <tr class="order-infor">
                            <td  class="col" colspan="4">
                                <div class="id pull-left"><?= $block->escapeHtml(__('Order Number:')) ?><?= /* @escapeNotVerified */ $_order->getRealOrderId() ?></div>
                                <div class="date-action pull-right">
                                    <span><?= /* @escapeNotVerified */ $block->formatDateTime($_order->getCreatedAt()) ?></span>
                                    <a href="<?= /* @escapeNotVerified */ $block->getViewUrl($_order) ?>" class="action view">
                                        <span><?= /* @escapeNotVerified */ __('View Order') ?></span>
                                    </a>
                                </div>
                            </td>
                        </tr>

                        <tr class="order-item">
                            <td>
                        <?php  foreach ($_items as $_item) { ?>
                                <div class="order-product">
                                    <a href="<?php echo $block->getProductUrl($_item->getProductId()) ?>">
                                    <img src="<?php echo $block->getImageUrl($_item->getProductId(), 'product_small_image'); ?>" />
                                    </a>
                                   <div class="product-infor">
                                       <span><?php echo $_item->getName(); ?></span>
                                       <span><?php echo 'X'.intval($_item->getQtyOrdered()); ?></span>
                                   </div>
                                </div>
                        <?php } ?>
                            </td>
                            <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="col total">
                               <span><?= $block->escapeHtml(__('Total:')) ?></span>
                                <?= /* @escapeNotVerified */ $_order->formatPrice($_order->getGrandTotal()) ?>
                            </td>
                            <td data-th="<?= $block->escapeHtml(__('Ship To')) ?>" class="col shipping">
                                <span><?= $block->escapeHtml(__('Ship To:')) ?></span>
                                <span><?= $_order->getShippingAddress() ? $block->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></span>
                            </td>
                            <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status">
                                <span><?= $block->escapeHtml(__('Status:')) ?></span>
                                <span><?= /* @escapeNotVerified */ $_order->getStatusLabel() ?></span>
                            </td>
                        </tr>

                    <tr style="display: none;">
                        <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="col id"><?= /* @escapeNotVerified */ $_order->getRealOrderId() ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date"><?= /* @escapeNotVerified */ $block->formatDate($_order->getCreatedAt()) ?></td>
                        <?php $extra = $block->getChildBlock('extra.container'); ?>
                        <?php if ($extra): ?>
                            <?php $extra->setOrder($_order); ?>
                            <?= /* @noEscape */ $extra->getChildHtml() ?>
                        <?php endif; ?>
                        <td data-th="<?= $block->escapeHtml(__('Ship To')) ?>" class="col shipping"><?= $_order->getShippingAddress() ? $block->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="col total"><?= /* @escapeNotVerified */ $_order->formatPrice($_order->getGrandTotal()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status"><?= /* @escapeNotVerified */ $_order->getStatusLabel() ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                            <a href="<?= /* @escapeNotVerified */ $block->getViewUrl($_order) ?>" class="action view">
                                <span><?= /* @escapeNotVerified */ __('View Order') ?></span>
                            </a>
                            <?php if ($this->helper('Magento\Sales\Helper\Reorder')->canReorder($_order->getEntityId())) : ?>
                                <a href="#" data-post='<?php /* @escapeNotVerified */ echo
                                $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                    ->getPostData($block->getReorderUrl($_order))
                                ?>' class="action order">
                                    <span><?= /* @escapeNotVerified */ __('Reorder') ?></span>
                                </a>
                            <?php endif ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?= /* @escapeNotVerified */ __('You have placed no orders.') ?></span></div>
<?php endif ?>
</div>
