<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Sales\Block\Adminhtml\Order\Create\Form $block */
?>
<form id="edit_form" action="<?php /* @escapeNotVerified */ echo $block->getSaveUrl() ?>" method="post">
    <?php echo $block->getBlockHtml('formkey')?>
    <div id="transaction-create-data" data-load-base-url="<?php /* @escapeNotVerified */ echo $block->getLoadBlockUrl() ?>" style="display:<?php /* @escapeNotVerified */ echo $block->getDataSelectorDisplay() ?>">
        <?php echo $block->getChildHtml('data') ?>
    </div>
    <script>
        require(['Mageplaza_Affiliate/js/create'], function(){
            window.transaction = new AffiliateCreate(
                    {
                        dataContainer: '#transaction-create-data',
                        customerContainer: '#transaction-customer-selector',
                        hideButton: '#back_transaction_top_button',
                        showButton: "#save_transaction_top_button, #reset_transaction_top_button"
                    }
            );
        });
    </script>
    <div id="transaction-customer-selector" class="fieldset-wrapper order-customer-selector" style="display:<?php /* @escapeNotVerified */ echo $block->getCustomerSelectorDisplay() ?>">
        <?php echo $block->getChildHtml('customer.grid.container') ?>
    </div>
</form>