<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$productImageHelper = $objectManager->get('Silk\Catalog\Helper\ProductImage');
?>
<?php /* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Multi */ ?>
<?php $_option = $block->getOption() ?>
<?php $_selections = $_option->getSelections() ?>
<div class="field option <?= ($_option->getRequired()) ? ' required': '' ?>">
    <label class="label" for="bundle-option-<?= /* @escapeNotVerified */ $_option->getId() ?>">
        <span><?= $block->escapeHtml($_option->getTitle()) ?></span>
    </label>
    <div class="control">
        <?php if ($block->showSingle()): ?>
            <image src="<?= $productImageHelper->getImageUrlById( $_selections[0]->getId(), 'product_thumbnail_image', 'thumbnail' ); ?>" title="" />
            <?= /* @escapeNotVerified */ $block->getSelectionQtyTitlePrice($_selections[0]) ?>
            <input type="hidden"
                   name="bundle_option[<?= /* @escapeNotVerified */ $_option->getId() ?>]"
                   value="<?= /* @escapeNotVerified */ $_selections[0]->getSelectionId() ?>"/>
        <?php else: ?>
            <select multiple="multiple"
                    size="5"
                    id="bundle-option-<?= /* @escapeNotVerified */ $_option->getId() ?>"
                    name="bundle_option[<?= /* @escapeNotVerified */ $_option->getId() ?>][]"
                    data-selector="bundle_option[<?= /* @escapeNotVerified */ $_option->getId() ?>][]"
                    class="bundle-option-<?= /* @escapeNotVerified */ $_option->getId() ?> multiselect product bundle option change-container-classname"
                    <?php if ($_option->getRequired()) echo 'data-validate={required:true}' ?>>
                <?php if(!$_option->getRequired()): ?>
                    <option value=""><?= /* @escapeNotVerified */ __('None') ?></option>
                <?php endif; ?>
                <?php foreach ($_selections as $_selection): ?>
                    <option value="<?= /* @escapeNotVerified */ $_selection->getSelectionId() ?>"
                            data-image="<?= $productImageHelper->getImageUrlById( $_selection->getId(), 'product_thumbnail_image', 'thumbnail' ); ?>"
                            <?php if ($block->isSelected($_selection)) echo ' selected="selected"' ?>
                            <?php if (!$_selection->isSaleable()) echo ' disabled="disabled"' ?>>

                        <?= /* @escapeNotVerified */ $block->getSelectionQtyTitlePrice($_selection, false) ?>
                    </option>
                <?php endforeach; ?>
            </select>
        <?php endif; ?>
    </div>
</div>
