<?php
/**
* @copyright Copyright (c) 2016 www.magebuzz.com
*/
?>
<?php
$enableFacebook = $block->_scopeConfig->getValue('socialshare/facebook/enable_facebook', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
$enableTwitter = $block->_scopeConfig->getValue('socialshare/twitter/enable_twitter', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
$enableGooglePlus = $block->_scopeConfig->getValue('socialshare/googleplus/enable_google_plus', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
$enablePinit = $block->_scopeConfig->getValue('socialshare/pinitsharing/enable_pinit', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
?>

<div class="magebuzz-social">

</div>
