<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
<?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;


?>

<?php

$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();

$storeManager =$objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$currency = $objectManager->get('\Magento\Directory\Model\Currency');

$store = $storeManager->getStore();

$cur =  $store->getWebsite()->getBaseCurrency()->getCurrencySymbol();


?>
<div class="home-products">
    <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
            <?php foreach ($items as $_item): ?>
                        <div class="item">
							<div class="img-box">
                            <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
                                <?= $block->getImage($_item, $image)->toHtml() ?>
                            </a>
							</div>
                            <div class="info-content">
                                <span class="product-name">
                                  <?= $block->escapeHtml($_item->getName()) ?>
                                </span>
                                <?php if ($templateType): ?>
                                    <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>
								<div class="price-box">
								<?php 
								$FinalPrice = $block->escapeHtml($_item->getFinalPrice()); 
								$price = $block->escapeHtml($_item->getPrice());
							
								?>
								<span class="final-price"><?= $cur ?><?= $FinalPrice ?></span>
									 <?php if($FinalPrice != $price): ?>
									<span class="prcie"><?= $cur ?><?= $price ?> - <?= $cur ?><?= $FinalPrice ?></span>
									<?php endif ?>
								</div>
								

                            </div>
                        </div>
                    
         <?php endforeach ?>


</div>
<?php endif;?>
