<?php $_element = $block->getElement() ?>

<div class="commission-tree">
    <fieldset id="<?php echo $_element->getHtmlId() ?>" class="fieldset">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo $_element->getLegend() ?></span></legend>
        <br>
		<?php if ($_element->getComment()): ?>
			<div class="messages">
            <div class="message message-notice"><?php echo $block->escapeHtml($_element->getComment()) ?></div>
        </div>
		<?php endif; ?>
		<div class="commission-tree-wrapper">
        <?php echo $_element->getChildrenHtml() ?>
    </div>
    </fieldset>
</div>
