<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php $_product = $block->getProduct() ?>
<?php if ($_product->isSaleable() && $block->hasOptions()):?>
    <div class="bundle-actions">
        <button id="bundle-slide"
                         class="action primary customize"
                         type="button">
            <span><i class="fa fa-sort-down"></i><?= /* @escapeNotVerified */ __('Product Accessories (click here)') ?></span>
        </button>
    </div>
<?php endif;?>
