<?php
namespace Dotsquares\Imexport\Model\Table;

class Csvcontent extends \Dotsquares\Imexport\Model\Functional\Export
{
    public function getCSVvalue($order)
    {
        $content = array();
        $shippingAddress = !$order->getIsVirtual() ? $order->getShippingAddress() : null;
        $billingAddress = $order->getBillingAddress();
        if(!$shippingAddress)
        $shippingAddress = $billingAddress;
        $credit_detail = $this->getCreditMemoDetail($order);
        $content = array(
            $order->getIncrementId(), 
            $order->getData('customer_email'),
            $this->formatText($order->getData('customer_firstname')),
            $this->formatText($order->getData('customer_lastname')),
            $this->formatText($order->getData('customer_prefix')),
            $this->formatText($order->getData('customer_middlename')),
            $this->formatText($order->getData('customer_suffix')),
            $order->getData('customer_taxvat'),
            $order->getData('created_at'),
            $order->getData('updated_at'),
            $this->getInvoiceDate($order),
            $this->getShipmentDate($order),
            $this->getCreditmemoDate($order),
            $order->getData('tax_amount'),
            $order->getData('base_tax_amount'),
            $order->getData('discount_amount'),
            $order->getData('base_discount_amount'),
            $order->getData('shipping_tax_amount'),
            $order->getData('base_shipping_tax_amount'),
            $order->getData('base_to_global_rate'),
            $order->getData('base_to_order_rate'),
            $order->getData('store_to_base_rate'),
            $order->getData('store_to_order_rate'),
            $order->getData('subtotal_incl_tax'),
            $order->getData('base_subtotal_incl_tax'),
            $order->getData('coupon_code'),
            $order->getData('shipping_incl_tax'),
            $order->getData('base_shipping_incl_tax'),
            $this->getShippingMethod($order),
            $order->getData('shipping_amount'),
            $order->getData('subtotal'),
            $order->getData('base_subtotal'),
            $order->getData('grand_total'),
            $order->getData('base_grand_total'),
            $order->getData('base_shipping_amount'),
            $credit_detail['adjustment_positive'],
            $credit_detail['adjustment_negative'],
            $credit_detail['shipping_amount'],
            $credit_detail['base_shipping_amount'],
            $credit_detail['subtotal'],
            $credit_detail['base_subtotal'],
            $credit_detail['tax_amount'],
            $credit_detail['base_tax_amount'],
            $credit_detail['discount_amount'],
            $credit_detail['base_discount_amount'],
            $order->getData('store_id'),
            $order->getStatus(),
            $order->getState(),
            $order->getHoldBeforeState(),
            $order->getHoldBeforeStatus(),
            $order->getData('store_currency_code'),
            $order->getData('base_currency_code'),
            $order->getData('order_currency_code'),
            $order->getData('total_paid'),
            $order->getData('base_total_paid'),
            $order->getData('is_virtual'),
            $order->getData('total_qty_ordered'),
            $order->getData('remote_ip'),
            $order->getData('total_refunded'),
            $order->getData('base_total_refunded'),
            $order->getData('total_canceled'),
            $order->getData('total_invoiced'),
            $order->getData('customer_id'),
            $this->formatText($order->getBillingAddress()->getData('prefix')),
            $this->formatText($order->getBillingAddress()->getData('firstname')),
            $this->formatText($order->getBillingAddress()->getData('middlename')),
            $this->formatText($order->getBillingAddress()->getData('lastname')),
            $this->formatText($order->getBillingAddress()->getData('suffix')),
            $this->formatText($order->getBillingAddress()->getData('street')),
            $this->formatText($order->getBillingAddress()->getData('city')),
            $this->formatText($order->getBillingAddress()->getData('region')),
            $this->formatText($order->getBillingAddress()->getData('country_id')),
            $order->getBillingAddress()->getData('postcode'),
            $order->getBillingAddress()->getData('telephone'),
            $this->formatText($order->getBillingAddress()->getData('company')),
            $order->getBillingAddress()->getData('fax'),
            $order->getData('customer_id'),
            $shippingAddress->getData('prefix'),
            $this->formatText($shippingAddress->getData('firstname')),
            $this->formatText($shippingAddress->getData('middlename')),
            $this->formatText($shippingAddress->getData('lastname')),
            $this->formatText($shippingAddress->getData('suffix')),
            $this->formatText($shippingAddress->getData('street')),
            $this->formatText($shippingAddress->getData('city')),
            $this->formatText($shippingAddress->getData('region')),
            $shippingAddress->getData('country_id'),
            $shippingAddress->getData('postcode'),
            $shippingAddress->getData('telephone'),
            $this->formatText($shippingAddress->getData('company')),
            $shippingAddress->getData('fax'),
            $this->getPaymentMethod($order)
        ); 
        return $content;
    }
}