<?php
$_htmlId   = $block->getHtmlid();
$inputName = $block->getName();
$value= $block->getConfigData();
?>

<div class="grid" id="<?php echo $_htmlId ?>">
    <table cellpadding="0" cellspacing="0" class="border">
        <tbody>
            <tr class="headings" id="headings<?php echo $_htmlId ?>">
				<th><?php echo __('Payment Method') ?></th>
				<th><?php echo __('Fee') ?></th>
				<th><?php echo __('Active') ?></th>
            </tr>
			<?php foreach ($block->getArrayRows() as $_rowId => $_row) : ?>
			<?php if(!isset($value[$_rowId])){
				$value[$_rowId]['fee'] = 0;
				$value[$_rowId]['active'] = 1;
			} ?>
				<tr id="<?php echo $_rowId ?>">
					<td style="width: 165px">
						<span><?php echo $_row ?></span>
						<input type="hidden" name="<?php echo $inputName . '[' . $_rowId . '][label]' ?>" value="<?php echo $_row ?>" />
					</td>

					<td>
						<input type="text" name="<?php echo $inputName . '[' . $_rowId . '][fee]' ?>" value="<?php echo isset($value[$_rowId]['fee']) ? $value[$_rowId]['fee'] : 0?>" style="width: 50px"/>
					</td>
					<td>
						<select name="<?php echo $inputName . '[' . $_rowId . '][active]' ?>" style="width: 50px">
							<option value="0" <?php echo !$value[$_rowId]['active'] ? 'selected' : '' ?>><?php echo __('No') ?></option>
							<option value="1" <?php echo $value[$_rowId]['active'] ? 'selected' : '' ?>><?php echo __('Yes') ?></option>
						</select>
					</td>
				</tr>
			<?php endforeach; ?>
        </tbody>
    </table>
	<input type="hidden" name="<?php echo $inputName ?>[__empty]" value="" />
</div>
