<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<div class="box-tocart sasdf">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
            <div class="field qty">
                <div class="control">
                    <div class="number-box">
                        <span class="less"></span>
                        <input type="number"
                               name="qty"
                               id="qty"
                               min="1"
                               value="<?= /* @escapeNotVerified */
                               $block->getProductDefaultQty() * 1 ?>"
                               title="<?= /* @escapeNotVerified */
                               __('Qty') ?>"
                               class="input-text qty"
                               data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                        <span class="plus"></span>
                    </div>
                </div>
            </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= /* @escapeNotVerified */
                    $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?= /* @escapeNotVerified */
                    $buttonTitle ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>

        <?php if( $_product->isSaleable() ) : ?>
        <span class="action toCheckout"><?= $block->escapeHtml(__('check out')) ?></span>
        <?php elseif( $_product->getData('stockout_info') ) : ?>
        <a href="javascript:void(0);" class="action toCheckout out-stock"><?= $block->escapeHtml(__($_product->getData('stockout_info'))) ?></a>
        <?php endif; ?>
    </div>
</div>
<input type="hidden" value="1" name="checkout"  disabled />
<?php if ($block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }

    </script>
<?php else : ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }

    </script>
<?php endif; ?>
