<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Newsletter\Block\Subscribe $block */

?>
<div class="block newsletter">
    <div class="title"><strong><?= $block->escapeHtml(__('Newsletter')) ?></strong></div>
    <div class="content">
        <form class="form subscribe"
              novalidate
              action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
              method="post"
              data-mage-init='{"validation": {"errorClass": "mage-error"}}'
              id="newsletter-validate-detail">
            <div class="field newsletter">
                <label class="label" for="newsletter"><span><?= $block->escapeHtml(__('Sign Up for Our Newsletter:')) ?></span></label>
                <div class="control">
                    <input name="email" type="email" id="newsletter"
                           placeholder="<?= $block->escapeHtmlAttr(__('Email Address*')) ?>"
                           data-validate="{required:true, 'validate-email':true}"/>
                    <div for="newsletter" generated="true" class="mage-error" id="newsletter-error"></div>
                </div>
            </div>
            <div class="actions">
                <button class="action subscribe primary" title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>" type="submit">
                    <span><?= $block->escapeHtml(__('Join')) ?></span>
                </button>
            </div>
        </form>
        <p>
		<?= $block->escapeHtml(__('Sign me up to receive emails on new product arrivals, special offers and exclusive events.')) ?>
		
		</p>
    </div>
</div>
